config/routes.rb
Smartdiag::Application.routes.draw do
  resources :users

  resources :events

  resources :users do
    resources :events
  end

  root :to => 'users#index'

end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :bdate, :first_name, :height, :last_name, :weight, :user_id
  has_many :events, dependent: :destroy
  validates :bdate, :first_name, :height, :last_name, :weight, presence: true
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # GET /users
  # GET /users.json
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])
    @time_now = Time.now.utc.at_midnight

    @event_data = Array.new
    @activity_data = Array.new
    @user.events.each do |event|
      if event.event_type == 3
        date_start = (event.activity_since.utc.to_f*1000.0).to_i
        # date_end = (event.entered_at.utc.to_f*1000.0).to_i
        @activity_data.push({x: date_start, y: event.activity_type, name: ACTIVITY_TYPE[event.activity_type]})
        # @activity_data.push({x: date_end, y: event.activity_type, name: ACTIVITY_TYPE[event.activity_type]})
      else
        date = (event.entered_at.utc.to_f*1000.0).to_i
        @event_data.push({x: date, y: (event.event_type+6), name: EVENT_TYPE[event.event_type]})
      end
    end


    @h = LazyHighCharts::HighChart.new('graph') do |f|
      f.chart( zoomType: 'x')
      f.title( text: @user.first_name + " " + @user.last_name + ' ' + 'activity and events')
      f.tooltip(
      #           useHTML: true,
      #           headerFormat: '<small>{point.key} + {point.name} </small><table>',
      #           pointFormat: "<tr><td style=\"color: {series.color}\">{series.name}: </td>" + "<td style=\"text-align: right\"><b>{point.y}</b></td></tr>",
                crosshairs: true,                followPointer: true,
                xDateFormat: '%Y-%m-%d',
                shared: true,
      #           footerFormat: '</table>'
                )

      f.yAxis(
        min: 0,
        max: 11,
        categories: [nil, "Steady", "Walking", "Biking", "Running", "", "Pain", "Meal", "Medicine", "Activity Change", "Other", ""],
        minorGridLineWidth: 1,
        gridLineWidth: 1,
        alternateGridColor: nil,
        tickInterval: 1,
        minTickInterval: 1,
        tickmarkPlacement: 'on',
        plotBands: [{
                      from: 0,
                      to: 5,
                      color: 'rgba(68, 170, 213, 0.1)',
                      label: {
                        text: 'Activity',
                        style: {
                          color: '#606060'
                        }
                      }
                    }, {
                      from: 5,
                      to: 10,
                      color: 'rgba(0, 0, 0, 0)',
                      label: {
                        text: 'Event',
                        style: {
                          color: '#606060'
                        }
                      }
                    }
                    ]
      )
      f.xAxis type: 'datetime'

      f.series(type: 'line', :name=>'Activity', :data=>@activity_data,  pointStart: (@time_now.to_f*1000.0).to_i, step: "left")
      f.series(type: 'line', lineWidth: 0, :name=>'Event', :data=>@event_data,  pointStart: (@time_now.to_f*1000.0).to_i)
    end

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end

  def chart_gen

  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :first_name %><br />
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br />
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label :bdate %><br />
    <%= f.date_select :bdate, order: [:day, :month, :year], start_year: 1900, end_year: Time.now.year %>
  </div>
  <div class="field">
    <%= f.label :weight %><br />
    <%= f.number_field :weight %>
  </div>
  <div class="field">
    <%= f.label :height %><br />
    <%= f.number_field :height %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table class="table table-condensed table-hover table-striped">
  <tr>
    <th>Id</th>
    <th>First name</th>
    <th>Last name</th>
    <th>Bdate</th>
    <th>Weight</th>
    <th>Height</th>
    <th></th>
<!--     <th></th>
    <th></th> -->
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.id %></td>
    <td><%= user.first_name %></td>
    <td><%= user.last_name %></td>
    <td><%= user.bdate %></td>
    <td><%= user.weight %></td>
    <td><%= user.height %></td>
    <td><%= link_to 'Show', user %></td>
    <!-- <td><%= link_to 'Edit', edit_user_path(user) %></td>
    <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td> -->
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<head>
<script>

  $(document).ready(function() {

    var date = new Date();
    var d = date.getDate();
    var m = date.getMonth();
    var y = date.getFullYear();

    $('#calendar').fullCalendar({
      header: {
        left: 'prev,next today',
        center: 'title',
        right: 'month,agendaWeek,agendaDay'
      },
      editable: false,
      events: [

        <% @user.events.each do |event| %>
          <% unless event.event_type == 3 %>
            {
            title: '<%= EVENT_TYPE[event.event_type] %>',
            start: new Date(<%= event.get_start_datetime_calendar if event %>),
            end: new Date(<%= event.get_end_datetime_calendar %>),
            allDay: false,
            url: '<%= user_event_path(@user,event) %>'
            },
          <% end %>
        <% end %>
        ]
    });

  });

</script>

</head>

<p id="notice"><%= notice %></p>

<!-- <p>
  <b>Id:</b>
  <%= @user.id %>
</p>

<p>
  <b>First name:</b>
  <%= @user.first_name %>
</p>

<p>
  <b>Last name:</b>
  <%= @user.last_name %>
</p>

<p>
  <b>Bdate:</b>
  <%= @user.bdate %>
</p>

<p>
  <b>Weight:</b>
  <%= @user.weight %>
</p>

<p>
  <b>Height:</b>
  <%= @user.height %>
</p> -->



  <div class="span10 offset1">
    <%= high_chart("chart", @h) do |c| %>
    <%=   %>
    <% end %>
  </div>
  <br>
  <br>
<h2>User's events</h2>
<table class="table table-condensed table-hover table-striped">

   <tr>
    <th>Entered at</th>
    <th>Event type</th>
    <th>Body part</th>
    <th>Level</th>
    <th>Description</th>
    <th>Quantity</th>
    <th>Temperature</th>
    <th>Drugs</th>
    <th>Event description</th>
    <th>Activity type</th>
    <th>Activity since</th>
    <th></th>
  </tr>

<% @user.events.each do |event| %>
  <% unless event.event_type == 3 %>
    <tr>
      <td><%= event.entered_at %></td>
      <td><%= EVENT_TYPE[event.event_type] %></td>
      <td><%= BODY_PART[event.body_part.to_i] %></td>
      <td><%= event.level %></td>
      <td><%= DESCRIPTION[event.description.to_i] %></td>
      <td><%= QUANTITY[event.quantity.to_i] %></td>
      <td><%= TEMPERATURE[event.temperature.to_i] %></td>
      <td><%= event.drugs %></td>
      <td><%= event.event_description %></td>
      <td><%= ACTIVITY_TYPE[event.activity_type.to_i] %></td>
      <td><%= event.activity_since %></td>
      <td class="list_actions"><%= link_to 'Show', user_event_path(@user,event) %></td>
    </tr>
  <% end %>
<% end %>


</table>
<br>
<div id='calendar'></div>